### ISSUE TITLE
ScribbleFill does not fill correctly according to the description provided

### ISSUE THREAD

**Issue by sanj94** [generative-light/p5.scribble.js#7] opened 2017-03-21 22:31 UTC
ScribbleFill for 90 degrees fill dots on the border of the figure only because the scribbleLine recieves the same to coordinates for the lines. The scribbleFill for other angles fill outside of the specified area.

**Comment by jawu** [comment] 2017-04-01 16:32
Thank you for opening this issue.
Could you please provide a sample sketch that shows this incorrect behavior?
In a simple test with angle=90 I couldn't find disfuntion.

**Comment by sanj94** [comment] 2017-04-17 21:58
![scribblefill](https://cloud.githubusercontent.com/assets/11560164/25106454/83f6f37a-2397-11e7-82fb-3a5d1ef7f11c.png)

**Comment by sanj94** [comment] 2017-04-17 21:59
An image on running the example as is.
It seemed to be working 11 days ago but not anymore

**Comment by jawu** [comment] 2017-04-18 10:27
Is this a running version of the example code or are there any changes?
Which Browser do you use?

**Comment by sanj94** [comment] 2017-04-18 11:27
There are no changes. It is exactly what has been provided.
I am using chrome

**Comment by jawu** [comment] 2017-05-01 20:18
I am sorry but I cant reproduce this problem in chrome. I will close this issue now.
Please update your chrome browser and try again.

**Closed as completed by jawu** 2017-05-01 20:18 UTC
